### ISSUE TITLE
Filter system like HMCWraps.

### ISSUE THREAD

**Issue by NxTPanic** [HibiscusMC/HMCCosmetics#133] opened 2024-04-25 15:12 UTC
### Feature Description

I would love to see a filtering system like HMCWraps on HMCCosmetic.

Filtering  all, Unlocked cosmetics.
Previous page
Next page
Go back to main menu.

**Comment by LoJoSho** [comment] 2024-04-25 16:49
Duplicate of #48

**Closed as not planned by LoJoSho** 2024-04-25 16:49 UTC
Labels: enhancement
