### ISSUE TITLE
[FEATURE] Gesturing in Wardrobes

### ISSUE THREAD

**Issue by SalomonPicos** [HibiscusMC/HMCCosmetics#86] opened 2023-03-25 16:17 UTC
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

Hello. I would like to send 2 suggestions that i i think would make the plugin 10 times better! Thanks for your time!

~~1: Adding the possiblity for player to move view when emoting. Right now when you emote your view get stuck and you cant' really enjoy the emote. Adding the possibility to move view would allow player to look at the emote 360 and it would be way better.~~ Duplicate of #68 

2: Adding the possibile to preview gestures in wardrobe too. + I think adding the possibility to decide what to preview in wardrobe would be amazing too. So for example being able to make a wardrobe just for gestures or for hats, or for hats AND gestures. So yeah, being able to decide what to show inside every single wardrobe!

Thanks again for your time, hope you'll take in consideration these suggestions!

### Config Changes

Wardrobe Gesture (?)

Option to decide what to show inside a single wardrobe

**Comment by LoJoSho** [comment] 2023-03-25 18:09
Partial duplicate of #68

**Closed as not planned** 2024-03-11 13:41 UTC
Labels: enhancement, help wanted
