### ISSUE TITLE
automatic

### ISSUE THREAD

**Issue by dinobossytnew** [HibiscusMC/HMCCosmetics#148] opened 2024-07-03 14:32 UTC
### Feature Description

Hello Mr. Dev,

A while ago, I purchased this plugin, and to be honest, it never seemed very interesting to me until now, when I tried it and loved it. However, it requires one essential function for its quick setup, which is the addition of an automatic way to read the cosmetics in that custom menu. For example, I have a menu called mochilas_2.yml, which is very beautiful, but every time I add or place cosmetics, I have to add them to the custom menu. If it runs out of slots, it's a pain to add another one, meaning it's very time-consuming. It should be done automatically, improving the efficiency and effectiveness of the plugin to earn its place as a premium with aspirations of greatness.

### Implementation Description

The new function aims to automate the already custom-created menus by the configurator, so instead of adding one by one, it should add the corresponding category, and all cosmetics of the category backpack will fill in the mochilas_2.yml.

**Comment by LoJoSho** [comment] 2024-07-03 23:57
Duplicate of #91

**Closed as not planned by LoJoSho** 2024-07-03 23:57 UTC
Labels: enhancement
