### ISSUE TITLE
New default Menu/GUI

### ISSUE THREAD

**Issue by BAttomic** [HibiscusMC/HMCCosmetics#134] opened 2024-05-03 02:28 UTC
### Feature Description

I think a good suggestion to improve the experience on HMCCosmetics would be to adopt a default menu similar to that of HMCWraps.
In my opinion, this change would greatly facilitate the navigation process within the system. Additionally, I believe community members would be quite pleased with the addition of these filters, as it would make it easier to find desired items.

### Implementation Description

This new menu could include permission filters, such as "Contains" or "Does not contain," as well as filters for alphabetical, rarity, and even numerical sorting based on custom-model-id.I imagine it would be very helpful to have a specific menu for each type of cosmetic, such as boots, leggings, chestplate, helmet, wings, and off-hand.

I believe you can take 100% inspiration from HMCWraps. Excellent default menu!

**Comment by LoJoSho** [comment] 2024-05-05 22:15
Duplicate of #133

**Closed as not planned by LoJoSho** 2024-05-05 22:15 UTC
Labels: enhancement
