### ISSUE TITLE
Sprays

### ISSUE THREAD

**Issue by AJIMA3** [HibiscusMC/HMCCosmetics#145] opened 2024-06-07 16:07 UTC
### Feature Description

I'd like to see sprays as cosmetics in the plugin and the ability to add my own custom sprays. Also to be able to customize how long these sprays will disappear after use or will not disappear at all. Also attached an example of the spray.
![unknown](https://github.com/HibiscusMC/HMCCosmetics/assets/134770058/d5c2bb74-ee46-448c-ad5d-da7038974d9d)

**Comment by LoJoSho** [comment] 2024-06-23 01:38
Duplicate of #101

**Closed as not planned by LoJoSho** 2024-06-23 01:38 UTC
Labels: enhancement
