### ISSUE TITLE
Additional PlaceholderAPI placeholders showing number of models

### ISSUE THREAD

**Issue by NekrosBurek** [HibiscusMC/HMCCosmetics#136] opened 2024-05-21 18:44 UTC
### Feature Description

It would be awesome to have a placeholderapi support showing information like:
- total number of cosmetics
- total number of in category 
- total unlocked cosmetics
- total unlocked cosmetics in category

**Comment by LoJoSho** [comment] 2024-05-21 18:48
This has already been added. Duplicate of #127.

**Closed as not planned by LoJoSho** 2024-05-21 18:48 UTC
Labels: duplicate, enhancement
