### ISSUE TITLE
[FEATURE] profiles 

### ISSUE THREAD

**Issue by magicelk235** [HibiscusMC/HMCCosmetics#90] opened 2023-04-03 07:30 UTC
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

I think you didn't understand what the idea was in #64 
Something 
![Screenshot_20230403_092628_Chrome](https://user-images.githubusercontent.com/120495924/229440991-713ac1b3-bd34-4365-91fe-938088bbad4f.jpg)
like this
This is feature from magic cosmetics

### Config Changes

New file called profile

**Comment by LoJoSho** [comment] 2023-04-03 13:41
I know what you meant. 

Duplicate of #64.

**Closed as not planned** 2023-04-03 13:41 UTC
